---
- name: Setting Kernel using sysctl module
  hosts: all
  gather_facts: false
  tasks:
  - name: sysctl settings 
    sysctl:
      name: "{{item.name}}"
      value: "{{item.value}}"
      state: present
    with_items:
      - { name: 'net.ipv4.ip_forward', value: '0' }
      - { name: 'vm.swappiness', value: '29' }
      - { name: 'net.ipv4.tcp_keepalive_intvl', value: '72' }
