---

- hosts: all
  become: yes
  tasks:
  
  - name: Verify process running
    shell: if ps -ef |grep httpd |grep -v grep ;then echo 'process_running';else echo 'process_not_running';fi
    register: app_process_check

  - name: print
    debug:
      msg: "{{ app_process_check.stdout }}"

  - name: Decide patching
    fail:
      msg: "{{ inventory_hostname }} have Application running.Please stop application"
    when: app_process_check.stdout == "process_running"

  - name: Update kernel
    yum:
      name: kernel
      state: latest
    when: app_process_check.stdout == "process_not_running" and ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    register: yum_update

  - name: Check if reboot required
    shell: KERNEL_NEW=$(rpm -q --last kernel |head -1 | awk '{print $1}' | sed 's/kernel-//'); KERNEL_NOW=$(uname -r); if [[ $KERNEL_NEW != $KERNEL_NOW ]]; then echo "reboot_needed"; else echo "reboot_not_needed"; fi
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    register: reboot_required

  - name: Rebooting
    command: shutdown -r +1  "Rebooting CentOS/RedHat Servers After Kernel Patching"
    async: 0
    poll: 0
    when: reboot_required.stdout == "reboot_needed" and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')
    register: reboot_started
    ignore_errors: true
