- hosts: all
  vars:
   user_pass: $6$TPDkpfHuoVc3dUM5$jypvKb.X5qzAvJYULd.2oXH7HbKxG5i6E2Khnu7FKzWieyCM6B.oxkgmTpBXFcTFEMGGGhXLqMuagCd0/ngA/.
  tasks:
   - name: update password
     user:
      name: "{{item.name}}"
      password: "{{item.value}}"
     with_items:
      - {name: 'zulu',value: '$6$q7g4TvmiFcw0xR8r$LFCLVtFDwRvW0NldSci2gRfpBWgMjj42vhAlcdEriUsFdUekDhLhxuwsrSHr0shAFqG6h5yidYS.rrkMNrlWN.' }
      - {name: 'zulu1',value: '$6$F5yBxhMQv8u3fTR1$bUSNBaEYChl62W788Z3SOLAH4OKPwtQ391vazoRqaHWNkjOdafSPv/cwGPfnUDbNZZbOSQtgD4quYzvK/OzfC0' }
      - {name: 'bbb',value: '$6$ghK/.E7S0TIRQa96$BmW7TyRjraxWWogajJMsWHqMNGeLPbOmZC6nM6w.kZrxGru1qJErYEaRDSH./4LF4qPpKBo43MYfq/XW6iOCo.' }

